name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

env:
  UPLOAD_BUILD: false

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        template: ["A","B"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
          qio platform install https://github.com/OS-Q/P51/releases/latest/download/package.zip

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: OS-Q/T51${{ matrix.template }}
          token: ${{ secrets.OSQ_REPO_TOKEN }}
          path: ${{ matrix.template }}

      - name: Build
        working-directory: ${{ matrix.template }}
        if: success()
        run: |
          pio run -d .

      - name: Upload
        if: env.UPLOAD_BUILD
        uses: actions/upload-artifact@v2
        with:
          name: build_${{ matrix.template }}_${{ matrix.os }}
          path: ${{ matrix.template }}/.pio/build

      - name: notification
        uses: stopstopstop/mqtt-action@master
        with:
          protocol: mqtt
          host: ${{secrets.MQTT_SERVER}}
          port: 1883
          username: ${{secrets.MQTT_USERNAME}}
          password: ${{secrets.MQTT_PASSWORD}}
          topic: ${{github.repository}}/${{ matrix.template }}/${{ matrix.os }}
          message: "templete build pass"
